jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Delete file 
        run: rm -f rss/emmathedilemma27.xml
      
      - name: Rename file 
        run: mv rss/_emmathedilemma27.xml rss/emmathedilemma27.xml

